### ISSUE TITLE
RFC [2.0] Roadmap

### ISSUE THREAD

**Issue by dukesx** [dukesx/afridi-dev#18]
## Roadmap

Here you will find, the direction in which we are headed. This is the game plan. This issue will be updated constantly and is FOR NOW, ONLY VALID TILL V2.0 release which is scheduled to release around Q3 2023 or Q1 2024 (if delayed).

 For V1.0, Our focus is more on CORE functionality to get things up and running. Later on we will focus on more ADVANCED features. 

Each one of the following features has been TAGGED with the version it's planned for. The roadmap is here and we are open to your suggestions and modifications. Everyone's opinion matters. We will try to consider and include as many features as possible.

- ### General Features
   - [x] #11      [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [x] #13      [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [ ] Chat System [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
       - [ ] 1 to 1 [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
       - [ ] Group/Room [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
   - [x] #14 [![Version - 20](https://img.shields.io/badge/Version-2.0-2ea44f)](https://)
       - [ ] #16  [![Version - 2.0](https://img.shields.io/badge/Version-20-2ea44f)](https://)
       - [x] #46 [![Version - 2.0](https://img.shields.io/badge/Version-20-2ea44f)](https://)
       - [x] #36

- ### Monetisation
     - [ ] Paid/Premium Content Subscription [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)

- ### Articles
   - [x] #36  [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [x] #12 [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [x] Reactions [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [x] Bookmarks [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [ ]  Courses [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)

- ### Users
   - [x] #10 [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [x] #47 [![Version - 1.0](https://img.shields.io/badge/Version-1.0-2ea44f)](https://)
   - [ ] Connections (ref - like LinkedIn) [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
   - [ ] Exclusive Content/Benefits (for self support) [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
      - [ ] Customised Subscription Packages (ref - OF) [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
      - [ ] Pledge System (one-time or monthly) [![Version - 2.0](https://img.shields.io/badge/Version-2.0-9775FA)](https://)
